-- Headers
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(1, 'Accessory');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(2, 'Air Intake');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(3, 'Auto Body Parts');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(4, 'Body Electrical');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(5, 'Body Mechanical & Trim');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(6, 'Brake');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(7, 'Climate Control');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(8, 'Clutch');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(9, 'Cooling System');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(10, 'Driveshaft & Axle');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(11, 'Engine Electrical');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(12, 'Engine Mechanical');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(13, 'Exhaust');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(14, 'Fuel Delivery');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(15, 'Interior Styling');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(16, 'Steering');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(17, 'Suspension');
INSERT INTO HEADER(HEADER_ID, HEADER_NAME) VALUES(18, 'Transmission');

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('HEADER', 18);

-- For Accessory header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(1, 'Bluetooth Adapter', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(2, 'Brake Bleeder Kit', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(3, 'Car Bra', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(4, 'Car Cover', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(5, 'Clutch Alignment Tool', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(6, 'Connectors', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(7, 'Deck Cover', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(8, 'Fuel Cap Tester Adapter', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(9, 'Hitch', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(10, 'Manual', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(11, 'Mud Flaps', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(12, 'Pet Pad', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(13, 'Rocker Panel Trim', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(14, 'Sealant', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(15, 'Serpentine Belt', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(16, 'Spark Plug Adapter', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(17, 'Spoiler', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(18, 'Storage Bag', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(19, 'Sun Shade', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(20, 'Trailer Wire Connector', 1);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(21, 'Window Visor', 1);

-- For Air Intake header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(22, 'Air Duct Hose', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(23, 'Air Filter', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(24, 'Air Intake Hose', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(25, 'Intake Manifold Gasket', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(26, 'Intake Plenum Gasket', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(27, 'Mass Air Flow Sensor', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(28, 'Mass Air Flow Sensor Adapter', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(29, 'Mass Air Flow Sensor Boot', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(30, 'PCV Valve', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(31, 'Throttle Body Gasket', 2);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(32, 'Throttle Position Sensor', 2);

-- For Auto Body Parts header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(33, 'A/C Condenser', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(34, 'Antenna', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(35, 'Back Up Light Switch', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(36, 'Bulb Socket', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(37, 'Bumper Absorber', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(38, 'Bumper Cover', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(39, 'Bumper Filler', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(40, 'Catalytic Converter', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(41, 'Control Arm', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(42, 'Corner Light', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(43, 'Door Jamb Switch', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(44, 'Door Lock', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(45, 'Driving Light', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(46, 'Fender', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(47, 'Fog Light', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(48, 'Fog Light Bulb', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(49, 'Fuel Filler Neck', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(50, 'Headlight', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(51, 'Headlight Bulb', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(52, 'Hood', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(53, 'Hood Latch', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(54, 'Light Bulb', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(55, 'Mirror', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(56, 'Radiator', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(57, 'Side Marker', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(58, 'Splash Shield', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(59, 'Spoiler', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(60, 'Turn Signal Switch', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(61, 'Washer Reservoir', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(62, 'Window Motor', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(63, 'Window Regulator', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(64, 'Wiper Blade', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(65, 'Wiper Linkage', 3);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(66, 'Wiper Motor', 3);

-- For Body Electrical header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(67, 'Back Up Light Switch', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(68, 'Battery', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(69, 'Brake Light Switch', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(70, 'Bulb Socket', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(71, 'Cigarette Lighter', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(72, 'Cigarette Lighter Socket', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(73, 'Clutch Pedal Ignition Switch', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(74, 'Corner Light', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(75, 'Driving Light', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(76, 'Flasher', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(77, 'Flasher Relay', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(78, 'Fog Light', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(79, 'Fog Light Bulb', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(80, 'Headlight', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(81, 'Headlight Bulb', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(82, 'LED Bulb', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(83, 'Light Bulb', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(84, 'Relay', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(85, 'Side Marker', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(86, 'Turn Signal Switch', 4);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(87, 'Wiring Harness', 4);

-- For Body Mechanical & Trim header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(88, 'Antenna', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(89, 'Bumper Absorber', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(90, 'Bumper Cover', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(91, 'Bumper Filler', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(92, 'Dash Cover', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(93, 'Door Jamb Switch', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(94, 'Door Lock', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(95, 'Fender', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(96, 'Gas Cap', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(97, 'Grille Assembly', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(98, 'Hood', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(99, 'Hood Latch', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(100, 'Mirror', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(101, 'Splash Shield', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(102, 'Washer Pump', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(103, 'Washer Reservoir', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(104, 'Weatherstrip Seal', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(105, 'Wheel', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(106, 'Wheel Lock Set', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(107, 'Wheel Seal', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(108, 'Window Crank', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(109, 'Window Motor', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(110, 'Window Regulator', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(111, 'Windshield Cover', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(112, 'Wiper Blade', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(113, 'Wiper Linkage', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(114, 'Wiper Motor', 5);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(115, 'Wiper Refill', 5);

-- For Brake header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(116, 'Brake Adjuster', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(117, 'Brake Bleed Screw', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(118, 'Brake Booster', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(119, 'Brake Booster Check Valve', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(120, 'Brake Caliper', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(121, 'Brake Caliper Piston', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(122, 'Brake Caliper Repair Kit', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(123, 'Brake Disc', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(124, 'Brake Disc and Pad Kit', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(125, 'Brake Drum', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(126, 'Brake Hardware Kit', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(127, 'Brake Line', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(128, 'Brake Master Cylinder', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(129, 'Brake Pad Set', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(130, 'Brake Shoe Set', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(131, 'Parking Brake Cable', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(132, 'Speed Sensor', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(133, 'Wheel Cylinder', 6);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(134, 'Wheel Cylinder Repair Kit', 6);

-- For Climate Control header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(135, 'A/C Caps and Valve Core Seal Kit', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(136, 'A/C Compressor', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(137, 'A/C Condenser', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(138, 'A/C Expansion Valve', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(139, 'A/C Filter', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(140, 'A/C Hose', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(141, 'A/C Idler Pulley', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(142, 'A/C Manifold Gasket', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(143, 'A/C O-Ring', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(144, 'A/C O-Ring and Gasket Seal Kit', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(145, 'A/C Receiver Drier', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(146, 'A/C Switch', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(147, 'Blower Control Switch', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(148, 'Blower Motor', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(149, 'Blower Motor Resistor', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(150, 'Heater Core', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(151, 'Heater Hose', 7);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(152, 'Refrigerant Oil', 7);

-- For Clutch header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(153, 'Clutch Cable', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(154, 'Clutch Disc', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(155, 'Clutch Kit', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(156, 'Clutch Release Arm', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(157, 'Flywheel', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(158, 'Flywheel Shim', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(159, 'Pilot Bearing', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(160, 'Pilot Bushing', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(161, 'Release Bearing', 8);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(162, 'Release Bearing Retain. Spring', 8);

-- For Cooling System header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(163, 'A/C Compressor Oil', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(164, 'Auxiliary Fan Control Unit', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(165, 'Bypass Hose', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(166, 'Coolant Reservoir', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(167, 'Coolant Reservoir Cap', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(168, 'Coolant Reservoir Hose', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(169, 'Coolant Temperature Sensor', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(170, 'Cooling Fan Assembly', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(171, 'Engine Temperature Sensor', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(172, 'Fan Motor', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(173, 'Freeze Plug', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(174, 'Radiator', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(175, 'Radiator Cap', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(176, 'Radiator Cap Adapter', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(177, 'Radiator Drain Plug', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(178, 'Radiator Drain Plug Gasket', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(179, 'Radiator Hose', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(180, 'Temperature Sender', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(181, 'Temperature Sending Gauge Switch', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(182, 'Thermostat', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(183, 'Thermostat Gasket', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(184, 'Thermostat Housing Cover', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(185, 'Water Outlet', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(186, 'Water Pump', 9);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(187, 'Water Pump Gasket', 9);

-- For Driveshaft & Axle header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(188, 'Axle Assembly', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(189, 'Axle Nut', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(190, 'Axle Seal', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(191, 'Axle Shaft Bearing', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(192, 'Bearing', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(193, 'CV Boot', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(194, 'CV Boot Clamp', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(195, 'Differential Bearing', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(196, 'Differential Seal', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(197, 'Repair Sleeve', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(198, 'Seal', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(199, 'Wheel Bearing', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(200, 'Wheel Bearing Circlip', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(201, 'Wheel Hub', 10);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(202, 'Wheel Stud', 10);

-- For Engine Electrical header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(203, 'Alternator', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(204, 'Battery Cable', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(205, 'Distributor', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(206, 'Distributor Cap', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(207, 'Distributor O-Ring', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(208, 'Distributor Rotor', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(209, 'Engine Control Module', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(210, 'Ignition Coil', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(211, 'Ignition Lock Assembly', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(212, 'Ignition Lock Cylinder', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(213, 'Ignition Module', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(214, 'Ignition Switch', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(215, 'Power Transistor', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(216, 'Spark Plug', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(217, 'Spark Plug Seal', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(218, 'Spark Plug Tube', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(219, 'Spark Plug Wire', 11);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(220, 'Starter', 11);

-- For Engine Mechanical header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(221, 'Accessory Belt Adjust Pulley', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(222, 'Accessory Belt Idler Pulley', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(223, 'Cam Follower', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(224, 'Cam Gear', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(225, 'Crankshaft Gear', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(226, 'Crankshaft Pulley', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(227, 'Crankshaft Seal', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(228, 'Crankshaft Thrust Washer Set', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(229, 'Cylinder Head', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(230, 'Cylinder Head Bolt', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(231, 'Cylinder Head Gasket', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(232, 'Drive Belt', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(233, 'Engine Gasket Set', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(234, 'Engine Rebuild Kit', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(235, 'Exhaust Valve', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(236, 'Intake Valve', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(237, 'Main Bearing', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(238, 'Motor and Transmission Mount Bushing', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(239, 'Motor Mount', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(240, 'Oil Cooler', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(241, 'Oil Cooler Line', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(242, 'Oil Drain Plug', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(243, 'Oil Drain Plug Gasket', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(244, 'Oil Filler Cap', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(245, 'Oil Filter', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(246, 'Oil Filter Relocation Kit', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(247, 'Oil Pan', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(248, 'Oil Pan Gasket', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(249, 'Oil Pressure Switch', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(250, 'Oil Pump', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(251, 'Piston', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(252, 'Piston Pin Bushing Set', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(253, 'Piston Ring Set', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(254, 'Rear Main Seal', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(255, 'Rod Bearing', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(256, 'Rod Bearing Set', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(257, 'Seal Ring', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(258, 'T-Belt Tensioner Pulley', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(259, 'Timing Chain', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(260, 'Timing Chain Guide', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(261, 'Timing Chain Kit', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(262, 'Timing Chain Tensioner', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(263, 'Timing Cover', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(264, 'Timing Cover Gasket', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(265, 'Timing Cover Seal', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(266, 'Timing Guide Rail', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(267, 'Transmission Mount', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(268, 'Valve Cover Gasket', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(269, 'Valve Cover Grommet', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(270, 'Valve Cover Seal Washer', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(271, 'Valve Guide', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(272, 'Valve Lifter', 12);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(273, 'Valve Stem Seal', 12);

-- For Exhaust header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(274, 'Catalytic Converter', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(275, 'Catalytic Converter Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(276, 'Down Pipe', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(277, 'EGR Temperature Sensor', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(278, 'EGR Vacuum Controller', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(279, 'EGR Valve', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(280, 'EGR Valve Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(281, 'Exhaust Bracket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(282, 'Exhaust Clamp', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(283, 'Exhaust Flange Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(284, 'Exhaust Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(285, 'Exhaust Hanger', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(286, 'Exhaust Insulator', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(287, 'Exhaust Manifold Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(288, 'Exhaust Mount', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(289, 'Exhaust Pipe', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(290, 'Exhaust Pipe Gasket', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(291, 'Exhaust Seal Ring', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(292, 'Exhaust Tip', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(293, 'Header Pipe', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(294, 'Muffler', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(295, 'Oxygen Sensor', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(296, 'Oxygen Sensor Nut', 13);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(297, 'Spring And Bolt Kit', 13);

-- For Fuel Delivery header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(298, 'Emission Hose', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(299, 'Fuel Catalyst', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(300, 'Fuel Cut-Off Sensor', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(301, 'Fuel Filler Neck', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(302, 'Fuel Filter', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(303, 'Fuel Injection Plenum Gasket', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(304, 'Fuel Injector', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(305, 'Fuel Injector Cushion Ring', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(306, 'Fuel Injector O-Ring', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(307, 'Fuel Injector Repair Kit', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(308, 'Fuel Pressure Regulator', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(309, 'Fuel Pressure Regulator O-Ring', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(310, 'Fuel Pump', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(311, 'Fuel Pump Gasket', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(312, 'Fuel Pump O-Ring', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(313, 'Fuel Pump Switch', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(314, 'Fuel Sending Unit', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(315, 'Fuel Sending Unit Lock Ring', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(316, 'Fuel Tank', 14);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(317, 'Fuel Tank Lock Ring', 14);

-- For Interior Styling header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(318, 'Cargo Mat', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(319, 'Carpet Kit', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(320, 'Floor Mats', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(321, 'Pedal Pad', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(322, 'Power Programmer', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(323, 'Seat Bracket', 15);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(324, 'Seat Cover', 15);

-- For Steering header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(325, 'Horn', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(326, 'Power Steering Filter', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(327, 'Power Steering Hose', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(328, 'Power Steering Pressure Switch', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(329, 'Power Steering Pump', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(330, 'Power Steering Pump Repair Kit', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(331, 'Power Steering Seal', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(332, 'Power Steering Suction Hose', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(333, 'Steering Rack', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(334, 'Steering Rack Boot', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(335, 'Steering Rack Bushing', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(336, 'Steering Wheel Hub', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(337, 'Tie Rod Assembly', 16);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(338, 'Tie Rod End', 16);

-- For Suspension header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(339, 'Ball Joint', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(340, 'Bearing Race', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(341, 'Camber and Alignment Kit', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(342, 'Coil Spring Insulator', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(343, 'Coil Springs', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(344, 'Control Arm', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(345, 'Control Arm Bushing', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(346, 'Lateral Link', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(347, 'Master Bushing Kit', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(348, 'Shock Absorber and Strut Assembly', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(349, 'Shock and Strut Boot', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(350, 'Shock and Strut Mount', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(351, 'Strut Bearing', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(352, 'Strut Brace Quick Release Kit', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(353, 'Strut Mount Bracket', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(354, 'Suspension Bumper', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(355, 'Sway Bar Bushing', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(356, 'Sway Bar Link', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(357, 'Sway Bar Link Bushing', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(358, 'Sway Bar Link Washer', 17);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(359, 'Track Rod Bushing', 17);

-- For Transmission header
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(360, 'Automatic Transmission Filter', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(361, 'Automatic Transmission Fluid', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(362, 'Automatic Transmission Pan Gasket', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(363, 'Input Shaft Seal', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(364, 'Neutral Safety Switch', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(365, 'Oil Cooler Mounting Kit', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(366, 'Output Shaft Seal', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(367, 'Selector Shaft Seal', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(368, 'Shifter Bushing', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(369, 'Torque Converter', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(370, 'Torque Converter Seal', 18);
INSERT INTO SECTION(SECTION_ID, SECTION_NAME, HEADER_ID) VALUES(371, 'Transmission Gasket', 18);

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('SECTION', 371);

-- Attributes
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(1, 'Product Fit');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(2, 'Location');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(3, 'Series');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(4, 'Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(5, 'Design');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(6, 'Color Finish');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(7, 'Coverage');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(8, 'FitNote');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(9, 'Type');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(10, 'Best Climate');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(11, 'Car Cover Weight');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(12, 'Recommended Use');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(13, 'Notes');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(14, 'Side Mirror Pockets');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(15, 'Connector Gender');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(16, 'Class');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(17, 'Receiver Tube Size');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(18, 'Style');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(19, 'Maximum Gross Trailer Weight');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(20, 'Maximum Tongue Weight');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(21, 'Requires Drilling');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(22, 'Tube Shape');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(23, 'Binding');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(24, 'ISBN');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(25, 'Language');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(26, 'Pages');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(27, 'Mud Flap Shape');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(28, 'Attachment Style');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(29, 'Dimensions');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(30, 'Mounting Style');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(31, 'Width');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(32, 'Replaces OE Number');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(33, 'Filtration Efficiency Rating');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(34, 'Gasket Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(35, 'Condition');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(36, 'Part Number');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(37, 'Anticipated Ship Out Time');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(38, 'Quantity Sold');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(39, 'Availability');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(40, 'Replaces Partslink Number');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(41, 'Emissions');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(42, 'Tube Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(43, 'Ball Joint Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(44, 'Bushing Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(45, 'Assembly');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(46, 'Certification');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(47, 'Bulb Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(48, 'Light Source');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(49, 'Wiring Harness Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(50, 'Shape');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(51, 'Bulb Type');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(52, 'Diameter');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(53, 'Wattage');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(54, 'Molding Holes');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(55, 'Color Temperature');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(56, 'Beam Color');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(57, 'Operation');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(58, 'Folding Type');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(59, 'Heated');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(60, 'Built In Signal Light');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(61, 'Auto Dimming');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(62, 'Blind Spot Detection');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(63, 'Glass Type');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(64, 'Memory Recall');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(65, 'Puddle Light Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(66, 'Towing Mirror');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(67, 'Tank Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(68, 'Automatic Transmission Cooler');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(69, 'Configuration');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(70, 'Core Dimensions');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(71, 'Core Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(72, 'Engine Oil Cooler');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(73, 'Inlet Size');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(74, 'Number of Rows');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(75, 'Outlet Size');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(76, 'Replaces DPI Number');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(77, 'Controls Cruise Control');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(78, 'Controls Turn Signal Headlight');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(79, 'Controls Wiper Windshield Washer');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(80, 'Motor Included');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(81, 'Vehicle Body Type');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(82, 'Blade Color');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(83, 'Blade Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(84, 'Frame Color Finish');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(85, 'Frame Material');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(86, 'Length');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME) VALUES(87, 'Lumens');

-- Section to default Attributes mapping
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(1, 1);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(2, 1);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(2, 2);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 3);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 4);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 5);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 6);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 7);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(3, 8);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 3);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 4);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 6);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 9);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 1);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 10);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 11);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 12);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 13);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 14);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(4, 8);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(6, 1);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(6, 15);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(6, 13);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(6, 8);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(7, 3);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(7, 4);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(7, 6);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(7, 1);
INSERT INTO SECTION_ATTRIBUTES(SECTION_ID, ATTRIBUTE_ID) VALUES(7, 8);

-- Car
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(1, 1991, 'Nissan', 'Sentra', 'Base', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(2, 1991, 'Nissan', 'Sentra', 'Classic', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(3, 1991, 'Nissan', 'Sentra', 'E', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(4, 1991, 'Nissan', 'Sentra', 'GXE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(5, 1991, 'Nissan', 'Sentra', 'SE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(6, 1991, 'Nissan', 'Sentra', 'SE-R', '4 Cyl 2.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(7, 1991, 'Nissan', 'Sentra', 'XE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(8, 1992, 'Nissan', 'Sentra', 'Base', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(9, 1992, 'Nissan', 'Sentra', 'Classic', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(10, 1992, 'Nissan', 'Sentra', 'E', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(11, 1992, 'Nissan', 'Sentra', 'GXE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(12, 1992, 'Nissan', 'Sentra', 'SE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(13, 1992, 'Nissan', 'Sentra', 'SE-R', '4 Cyl 2.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(14, 1992, 'Nissan', 'Sentra', 'XE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(15, 1993, 'Nissan', 'Sentra', 'Base', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(16, 1993, 'Nissan', 'Sentra', 'Classic', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(17, 1993, 'Nissan', 'Sentra', 'E', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(18, 1993, 'Nissan', 'Sentra', 'GXE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(19, 1993, 'Nissan', 'Sentra', 'SE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(20, 1993, 'Nissan', 'Sentra', 'SE-R', '4 Cyl 2.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(21, 1993, 'Nissan', 'Sentra', 'XE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(22, 1994, 'Nissan', 'Sentra', 'Base', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(23, 1994, 'Nissan', 'Sentra', 'Classic', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(24, 1994, 'Nissan', 'Sentra', 'E', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(25, 1994, 'Nissan', 'Sentra', 'GXE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(26, 1994, 'Nissan', 'Sentra', 'SE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(27, 1994, 'Nissan', 'Sentra', 'SE-R', '4 Cyl 2.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(28, 1994, 'Nissan', 'Sentra', 'XE', '4 Cyl 1.6L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(29, 1991, 'Toyota', 'Supra', 'Base', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(30, 1991, 'Toyota', 'Supra', 'Turbo', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(31, 1991, 'Toyota', 'Celica', 'GT', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(32, 1991, 'Toyota', 'Celica', 'GTS', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(33, 1991, 'Toyota', 'Celica', 'ST', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(34, 1992, 'Toyota', 'Supra', 'Base', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(35, 1992, 'Toyota', 'Supra', 'Turbo', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(36, 1992, 'Toyota', 'Celica', 'GT', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(37, 1992, 'Toyota', 'Celica', 'GTS', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(38, 1992, 'Toyota', 'Celica', 'ST', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(39, 1993, 'Toyota', 'Supra', 'Base', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(40, 1993, 'Toyota', 'Supra', 'Turbo', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(41, 1993, 'Toyota', 'Celica', 'GT', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(42, 1993, 'Toyota', 'Celica', 'GTS', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(43, 1993, 'Toyota', 'Celica', 'ST', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(44, 1994, 'Toyota', 'Supra', 'Base', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(45, 1994, 'Toyota', 'Supra', 'Turbo', '6 Cyl 3.0L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(46, 1994, 'Toyota', 'Celica', 'GT', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(47, 1994, 'Toyota', 'Celica', 'GTS', '4 Cyl 2.2L');
INSERT INTO CAR(CAR_ID, YEAR, MAKE, MODEL, SUBMODEL, ENGINE) VALUES(48, 1994, 'Toyota', 'Celica', 'ST', '4 Cyl 2.2L');

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('CAR', 48);

-- AutoPart
INSERT INTO AUTO_PART(AUTO_PART_ID, NAME, DESCRIPTION, STATUS, QUANTITY, LIST_PRICE, ACTUAL_PRICE, UNIVERSAL, SECTION_ID, DATE_ADDED, DATE_APPROVED) VALUES(1, 'American Cylinder Head 1993 Nissan Sentra', 'Uncompromised quality and precision remanufacturing is what you get in every American Cylinder Head product. No need to hunt for a machine shop – remanufactured cylinder heads are kept in stock and delivered ready to install to get your vehicle back on the road in the least amount of time. American Cylinder Head has been providing the finest remanufactured cylinder heads for over 40 years and is a family owned and operated business with an endless commitment to product improvement and customer satisfaction.', 'PUBLISHED', 1, 328.13, 217.36, 0, 229, current_timestamp, current_timestamp)

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('AUTO_PART', 1);

INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(88, 'Material', 'Aluminum');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(89, 'Type', 'Assembled');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(90, 'Color Finish', 'Natural');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(91, 'Product Fit', 'Direct Fit');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(92, 'Quantity Sold', 'Sold Individually');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(93, 'Anticipated Ship Out Time', '1-2 Business Days');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(94, 'Part Number', 'AC238C1');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(95, 'Availability', 'In Stock');
INSERT INTO ATTRIBUTE(ATTRIBUTE_ID, NAME, VALUE) VALUES(96, 'FitNote', 'Alum');

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('ATTRIBUTE', 96);

INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 88)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 89)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 90)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 91)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 92)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 93)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 94)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 95)
INSERT INTO AUTO_PART_ATTRIBUTES(AUTO_PART_ID, ATTRIBUTE_ID) VALUES(1, 96)

INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 1)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 2)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 3)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 4)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 5)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 6)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 7)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 8)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 9)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 10)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 11)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 12)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 13)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 14)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 15)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 16)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 17)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 18)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 19)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 20)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 21)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 22)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 23)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 24)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 25)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 26)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 27)
INSERT INTO AUTO_PART_CARS(AUTO_PART_ID, CAR_ID) VALUES(1, 28)