INSERT INTO WORK_EXPERIENCE(WORK_EXPERIENCE_ID, NAME) VALUES(1, 'Skin White');
INSERT INTO WORK_EXPERIENCE(WORK_EXPERIENCE_ID, NAME) VALUES(2, 'Johnny Walker');
INSERT INTO WORK_EXPERIENCE(WORK_EXPERIENCE_ID, NAME) VALUES(3, 'Jack Daniels');
INSERT INTO WORK_EXPERIENCE(WORK_EXPERIENCE_ID, NAME) VALUES(4, 'Tanduay');
INSERT INTO WORK_EXPERIENCE(WORK_EXPERIENCE_ID, NAME) VALUES(5, 'Coors Light');

INSERT INTO HIBERNATE_SEQUENCES(SEQUENCE_NAME, SEQUENCE_NEXT_HI_VALUE) VALUES('WORK_EXPERIENCE', 5);